### ISSUE TITLE
<ignore>

### ISSUE THREAD

**Issue by kim-friis** [bregnvig/playgrounds#2]

**Comment by bregnvig** [comment]
The backend code is not part of this project. The post to the backend is included in the project. 

Example i `services.js`:

``` Javascript
.factory('Playground', function($resource) {
    return $resource('https://ratr-2015.appspot.com/location/:id');
  })
.factory('Rating', function($resource) {
  return $resource('https://ratr-2015.appspot.com/location/:id/rating');
});
```

They define a $resource. I know we did not talk about these.

In `app.js` we use these resource.

``` Javascript
new Rating($scope.model).$save({ id: $routeParams.id }, function() {
    $scope.ratings = Rating.query({ id: $routeParams.id });
    $scope.model = {};
    $scope.review.$setUntouched();
});
```

Have a look at [$resource](https://docs.angularjs.org/api/ngResource/service/$resource)

**Comment by kim-friis** [comment]
Ok, was just curious to see the backend code also :-)
